Remove redundant move
This was a warning (treated as error) with GCC 11:

	src/connection_pool.cpp:101:49: error: redundant move in initialization [-Werror=redundant-move]

MSVC produced another warning about the same move:

	C26478	Don't use std::move on constant variables.

Removed the move to make both compilers happy.

Fixes: https://github.com/scylladb/cpp-driver/issues/79